// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    allow_cors_domains: string;
    discord_webhook_url: string;
}
